"""Build-time vendor of the shared cjk-latin-space core into this package.

Copies core/src/cjk_latin_space/__init__.py to src/<pkg>/_cjk_latin_space.py so
the built sdist and wheel are self-contained: core is never a runtime dependency
and there is no path/workspace reference to resolve at install time. The copy is
made for both the sdist and wheel targets, so building a wheel from an already
built sdist works even though the core source lives outside the sdist — by then
the vendored copy is already inside it, and a missing source is tolerated.

The hook also supplies the wheel's own `_core.py`. The working tree's tracked
`_core.py` imports the live workspace core, which is what development needs and
what a wheel must not do, so the wheel target excludes that file and this hook
force-includes a shim in its place. Generating the shim rather than branching at
runtime is what removes the `sys.path` lookup from the published package: a
relative import is confined to the package's own `__path__`, so no installed
distribution providing a top-level `cjk_latin_space` can take over.
"""

import shutil
from pathlib import Path

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

_PACKAGE = "typst_cjk_latin_space_remover"
_VENDOR_DEST = f"src/{_PACKAGE}/_cjk_latin_space.py"
_CORE_SHIM_DEST = f"{_PACKAGE}/_core.py"
_CORE_SHIM = '''"""Resolve the vendored cjk-latin-space core inside a published wheel.

Generated by hatch_build.py. The relative import is what makes this module
unshadowable: it resolves within this package's `__path__` and never consults
`sys.path`. The working tree keeps a different `_core.py` that imports the live
workspace core; the wheel target excludes it in favour of this file.
"""

from ._cjk_latin_space import CJK_CLASS, squash

__all__ = ["CJK_CLASS", "squash"]
'''


class CustomBuildHook(BuildHookInterface):
    PLUGIN_NAME = "custom"

    def initialize(self, version, build_data):
        root = Path(self.root)
        source = (
            root / ".." / ".." / "core" / "src" / "cjk_latin_space" / "__init__.py"
        ).resolve()
        dest = root / _VENDOR_DEST
        if source.is_file():
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, dest)
        elif not dest.is_file():
            raise FileNotFoundError(
                f"core source {source} not found and no vendored copy at {dest}"
            )

        # Only a real wheel gets the shim. `target_name` alone does not identify
        # one: a PEP 660 editable install is also built through the wheel target,
        # and there the tracked `_core.py` is what must stay in effect. The shim
        # is written after the vendor step above so that a build with neither a
        # core source nor a vendored copy fails there, rather than shipping a
        # shim whose relative import has no module to reach.
        if version == "standard" and self.target_name == "wheel":
            shim = self._shim_path()
            shim.parent.mkdir(parents=True, exist_ok=True)
            shim.write_text(_CORE_SHIM)
            build_data["force_include"][str(shim)] = _CORE_SHIM_DEST

    def finalize(self, version, build_data, artifact_path):
        # The shim is scratch: it lives beside the built artifact only long
        # enough to be copied into it.
        self._shim_path().unlink(missing_ok=True)

    def _shim_path(self):
        return Path(self.directory) / f".core_shim_{_PACKAGE}.py"
