"""Build-time vendor of the shared cjk-latin-space core into this package.

Copies core/src/cjk_latin_space/__init__.py to src/<pkg>/_cjk_latin_space.py so
the built sdist and wheel are self-contained: core is never a runtime dependency
and there is no path/workspace reference to resolve at install time. The copy is
made for both the sdist and wheel targets, so building a wheel from an already
built sdist works even though the core source lives outside the sdist — by then
the vendored copy is already inside it, and a missing source is tolerated.

The hook also supplies the wheel's own `_core.py`. The working tree's tracked
`_core.py` prefers the live workspace core, which is what development needs and
what a wheel must not do, so the wheel target excludes that file and this hook
force-includes a shim in its place. The shim's import is relative, so it is
confined to the package's own `__path__` and never consults `sys.path`: no
installed distribution providing a top-level `cjk_latin_space` can take over.
"""

import shutil
import tempfile
from pathlib import Path

from hatchling.builders.hooks.plugin.interface import BuildHookInterface

_PACKAGE = "typst_cjk_latin_space_remover"
_VENDOR_DEST = f"src/{_PACKAGE}/_cjk_latin_space.py"
_CORE_SHIM_DEST = f"{_PACKAGE}/_core.py"
_CORE_SHIM = '''"""Resolve the vendored cjk-latin-space core inside a published wheel.

Generated by hatch_build.py. The relative import is what makes this module
unshadowable: it resolves within this package's `__path__` and never consults
`sys.path`. The working tree keeps a different `_core.py` that imports the live
workspace core; the wheel target excludes it in favour of this file.
"""

from ._cjk_latin_space import CJK_CLASS, squash

__all__ = ["CJK_CLASS", "squash"]
'''


class CustomBuildHook(BuildHookInterface):
    PLUGIN_NAME = "custom"

    def initialize(self, version, build_data):
        root = Path(self.root)
        source = (
            root / ".." / ".." / "core" / "src" / "cjk_latin_space" / "__init__.py"
        ).resolve()
        dest = root / _VENDOR_DEST
        if source.is_file():
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, dest)
        elif not dest.is_file():
            raise FileNotFoundError(
                f"core source {source} not found and no vendored copy at {dest}"
            )

        # Only a real wheel gets the shim. `target_name` alone does not identify
        # one: a PEP 660 editable install is also built through the wheel target,
        # and there the tracked `_core.py` is what must stay in effect. The shim
        # is written after the vendor step above so that a build with neither a
        # core source nor a vendored copy fails there, rather than shipping a
        # shim whose relative import has no module to reach.
        if version == "standard" and self.target_name == "wheel":
            # A temporary directory rather than the output directory, so nothing
            # is left where the artifacts land. Held on the instance so it
            # outlives this call; its finalizer removes the directory when the
            # build process exits, which also covers the paths where hatchling
            # never calls finalize -- a hooks-only build, and one whose
            # packaging step raises.
            self._shim_dir = tempfile.TemporaryDirectory(prefix="core-shim-")
            shim = Path(self._shim_dir.name) / "_core.py"
            shim.write_text(_CORE_SHIM)
            build_data["force_include"][str(shim)] = _CORE_SHIM_DEST
